config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  TYPES = %w{ new fix update }

  after_initialize :set_defaults

  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: { in: TYPES }

  def set_defaults
    self.published_at      ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
  include Noticed::Model
  belongs_to :recipient, polymorphic: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user

  Devise.omniauth_configs.keys.each do |provider|
    scope provider, ->{ where(provider: provider) }
  end

  def client
    send("#{provider}_client")
  end

  def expired?
    expires_at? && expires_at <= Time.zone.now
  end

  def access_token
    send("#{provider}_refresh_token!", super) if expired?
    super
  end


  def twitter_client
    Twitter::REST::Client.new do |config|
      config.consumer_key        = Rails.application.secrets.twitter_app_id
      config.consumer_secret     = Rails.application.secrets.twitter_app_secret
      config.access_token        = access_token
      config.access_token_secret = access_token_secret
    end
  end

  def twitter_refresh_token!(token); end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :masqueradable, :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :omniauthable

  has_one_attached :avatar
  has_person_name

  has_many :notifications, as: :recipient
  has_many :services
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  private

    def mark_as_read
      current_user.update(announcements_last_read_at: Time.zone.now)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  layout :layout_by_resource

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :masquerade_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :surname, :phone])
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :surname, :phone, :avatar])
    end


    def layout_by_resource
      if devise_controller? && resource_name == :user && action_name == 'new'
        'account'
      else
        'application'
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def terms
  end

  def privacy
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    # Convert the database records to Noticed notification instances so we can use helper methods
    @notifications = current_user.notifications.map(&:to_notification)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :set_service
    before_action :set_user

    attr_reader :service, :user

    def facebook
      handle_auth "Facebook"
    end

    def twitter
      handle_auth "Twitter"
    end

    def github
      handle_auth "Github"
    end

    private

    def handle_auth(kind)
      if service.present?
        service.update(service_attrs)
      else
        user.services.create(service_attrs)
      end

      if user_signed_in?
        flash[:notice] = "Your #{kind} account was connected."
        redirect_to edit_user_registration_path
      else
        sign_in_and_redirect user, event: :authentication
        set_flash_message :notice, :success, kind: kind
      end
    end

    def auth
      request.env['omniauth.auth']
    end

    def set_service
      @service = Service.where(provider: auth.provider, uid: auth.uid).first
    end

    def set_user
      if user_signed_in?
        @user = current_user
      elsif service.present?
        @user = service.user
      elsif User.where(email: auth.info.email).any?
        # 5. User is logged out and they login to a new account which doesn't match their old one
        flash[:alert] = "An account with this email already exists. Please sign in with that account before connecting your #{auth.provider.titleize} account."
        redirect_to new_user_session_path
      else
        @user = create_user
      end
    end

    def service_attrs
      expires_at = auth.credentials.expires_at.present? ? Time.at(auth.credentials.expires_at) : nil
      {
          provider: auth.provider,
          uid: auth.uid,
          expires_at: expires_at,
          access_token: auth.credentials.token,
          access_token_secret: auth.credentials.secret,
      }
    end

    def create_user
      User.create(
        email: auth.info.email,
        #name: auth.info.name,
        password: Devise.friendly_token[0,20]
      )
    end

  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger",
    }.fetch(type, "text-success")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: "alert-success",
      error: "alert-danger",
      alert: "alert-warning",
      notice: "alert-info"
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end
  
  def avatar_path(object, options = {})
    size = options[:size] || 180
    default_image = options[:default] || "mp"
    base_url =  "https://secure.gravatar.com/avatar"
    base_url_params = "?s=#{size}&d=#{default_image}"
    
    if object.respond_to?(:avatar) && object.avatar.attached? && object.avatar.variable?
      object.avatar.variant(resize_to_fill: [size, size, { gravity: 'Center' }])
    elsif object.respond_to?(:email) && object.email
      gravatar_id = Digest::MD5::hexdigest(object.email.downcase)
      "#{base_url}/#{gravatar_id}#{base_url_params}"
    else
      "#{base_url}/00000000000000000000000000000000#{base_url_params}"
    end
  end
end

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <%= link_to(
    "← Back to App",
    root_path,
    class: "navigation__link"
  ) %>

  <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource)) %>
  <% end %>
</nav>

app/views/admin/users/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { t("administrate.actions.show_resource", {name: page.page_title}) } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to "Login As User", masquerade_path(page.resource), class: "button" %>

    <%= link_to(
      "#{t("administrate.actions.edit")} #{page.page_title}",
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action? :edit %>
  </div>
</header>

<section class="main-content__body">
  <dl>
    <% page.attributes.each do |attribute| %>
      <dt class="attribute-label" id="<%= attribute.name %>">
      <%= t(
        "helpers.label.#{resource_name}.#{attribute.name}",
        default: attribute.name.titleize,
      ) %>
      </dt>

      <dd class="attribute-data attribute-data--<%=attribute.html_class%>"
          ><%= render_field attribute %></dd>
    <% end %>
  </dl>
</section>

app/views/announcements/index.html.erb
<h1>What's New</h1>

<div class="card">
  <div class="card-body">
    <% @announcements.each_with_index do |announcement, index| %>
      <% if index != 0 %>
        <div class="row"><div class="col"><hr /></div></div>
      <% end %>

      <div class="row announcement" id="<%= dom_id(announcement) %>">
        <div class="col-sm-1 text-center">
          <%= link_to announcements_path(anchor: dom_id(announcement)) do %>
            <strong><%= announcement.published_at.strftime("%b %d") %></strong>
          <% end %>
        </div>
        <div class="col">
          <strong class="<%= announcement_class(announcement.announcement_type) %>"><%= announcement.announcement_type.titleize %>:</strong>
          <strong><%= announcement.name %></strong>
          <%= simple_format announcement.description %>
        </div>
      </div>
    <% end %>

    <% if @announcements.empty? %>
      <div>Exciting stuff coming very soon!</div>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<header class="header">
<div class="row align-items-center">
    <div class="col-lg-5">
        <div class="hero-title pr-lg-5">
            
            <h1 class="hero-1-title mb-2 font-weight-normal line-height-1_4"> We offer only the <span class="text-success font-weight-medium">best</span></h1>
            <p class="mb-4 pb-2">Enjoy a comfortable atmosphere with various facilities available</p>

           
            <div class="input-group mb-2 mr-sm-2">
            <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="Search for services">
            <div class="input-group-prepend">
            <div class="input-group-text btn btn-success bg-success text-white">Search</div>
            </div>
  </div>
        </div>
    </div>
    <div class="col-lg-7">
        <div class="mt-5 mt-lg-0">
            <%# <img src="assets/imgs/hero-1-img.png" alt="" class="img-fluid mx-auto d-block"> %>
            <%= image_tag "medic.png", class: "img-fluid mx-auto d-block", alt: 'medic' %>
        </div>
    </div>
</div>
</header>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/acct_nav' %>
    <%= render 'shared/notices' %>

    <div class="container">
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/head' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/notices' %>


      <%= yield %>


    <%= render 'shared/footer' %>
  </body>
</html>

app/views/notifications/index.html.erb
<h1>Notifications</h1>

<ul>
  <% @notifications.each do |notification| %>
    <%# Customize your notification format here. We typically recommend a `message` and `url` method on the Notification classes. %>
    <%#= link_to notification.message, notification.url %>

    <li><%= notification.params %></li>
  <% end %>
</ul>

app/views/shared/_acct_nav.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-white h-150">
  <div class="container">
    <%= link_to '<i class="fas fa-long-arrow-alt-left"></i>'.html_safe, root_path, class: "navbar-brand" %>
    <%= link_to 'Sign up/Sign in', root_path, class: "navbar-brand" %>
    <%= link_to 'Sign up', root_path, class: "navbar-brand text-white " %>
    
    
    
  </div>
</nav>

app/views/shared/_footer.html.erb
<footer class="footer text-light d-flex align-items-center">
  <div class="container d-flex flex-wrap align-items-center justify-content-between">
    
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3"><%= link_to "Terms & Condition", terms_path, class: 'text-light' %></li>
      <!-- <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path, class: 'text-light' %></li> -->
    </ul>
    <h4>Amazing<span class="text-success">Health</span></h4>
    <span>© <%= Date.today.year %> amazinghealth</span>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= Rails.configuration.application_name %></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;900&display=swap" rel="stylesheet">
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("fas", "times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-white">
  <div class="container">
  
    <%= link_to 'Amazing<span class="text-success">Health</span>'.html_safe, root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0 mid-nav-items">
        <%= link_to 'Home', root_path, class: "nav-link" %>
        <%= link_to 'Section', root_path, class: "nav-link" %>
        <%= link_to 'Testimonials', root_path, class: "nav-link" %>
        <%= link_to 'HealthNews', root_path, class: "nav-link" %>
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>
        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="far fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>

          <li class="nav-item dropdown">
            <%= link_to "#", id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { target: "nav-account-dropdown", toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag avatar_path(current_user, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div id="nav-account-dropdown" class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <% if current_user.admin? && respond_to?(:admin_root_path) %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>